[tool.poetry]
name = "jodie"
version = "0.1.0"
description = "Jodie lets you add contacts to Contacts.app on macOS from command line"
authors = ["austin <tips@cia.lol>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
pyobjc = "10.2"
pyobjc-core = "10.2"
pyobjc-framework-addressbook = "10.2"
pyobjc-framework-contacts = "10.2"
pyobjc-framework-contactsui = "10.2"

[tool.poetry.scripts]
jodie-cli = "jodie.__main__:main"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
